spring.application.name=springAITest

spring.ai.openai.api-key=${OPENAI_API_KEY}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}


spring.ai.chat.memory.repository.jdbc.initialize-schema=never